# Generated by Django 3.2.13 on 2022-06-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtweet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('topic', models.CharField(max_length=100)),
                ('text', models.CharField(default='null', max_length=500)),
                ('date', models.DateField()),
                ('polarity', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='low', max_length=100)),
                ('url', models.CharField(default='null', max_length=500)),
                ('action', models.BooleanField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('retweet', models.IntegerField(default=0)),
                ('type', models.CharField(default='null', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
