# Generated by Django 3.2.13 on 2022-06-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtweet', '0002_auto_20220618_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
