# Generated by Django 3.2.13 on 2022-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtweet', '0003_alter_tweets_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='username',
            field=models.CharField(default='unidentified', max_length=100),
            preserve_default=False,
        ),
    ]
