# Generated by Django 3.2.13 on 2022-06-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtweet', '0004_tweets_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
